version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/www/evangelic-history/uploads:/app/uploads
    depends_on:
      - db
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/evangelical_history?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ZoNoV_DM1

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ZoNoV_DM1
      MYSQL_DATABASE: evangelical_history
    volumes:
      - db_data:/var/lib/mysql/

volumes:
  db_data:
